name: formbricks_flutter
description: "A comprehensive Flutter package for rendering and managing all Formbricks survey types in flutter apps. #Formbricks #NPS #promoter score #survey"
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_rating_bar: ^4.0.1
  file_picker: ^10.2.0 #For file uploads
  intl: ^0.20.2 #For date formatting
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1 #For picture selection
  reorderables: ^0.6.0 #For ranking questions
  url_launcher: any
  shared_preferences: any
  card_stack_widget: ^0.1.6
  flutter_widget_from_html: ^0.16.0
  pretty_http_logger: ^1.0.5
  chewie: ^1.12.1
  video_player: ^2.10.0
  dotted_border: ^3.1.0
  line_awesome_flutter: ^3.0.1
  mime_type: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  mockito: ^5.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # To add assets to your package, add an assets section, like this:
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  template_arbs:
    - lib/l10n/app_en.arb
    - lib/l10n/app_fr.arb
    - lib/l10n/app_es.arb
    - lib/l10n/app_ar.arb
    - lib/l10n/app_zh.arb
    - lib/l10n/app_ja.arb
    - lib/l10n/app_pt.arb
    - lib/l10n/app_sw.arb
    - lib/l10n/app_de.arb
  output_dir: lib/generated
